/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreaLayananRouteImport } from './routes/area-layanan'
import { Route as ArmadaRouteImport } from './routes/armada'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaLayananRoute = AreaLayananRouteImport.update({
  id: '/area-layanan',
  path: '/area-layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmadaRoute = ArmadaRouteImport.update({
  id: '/armada',
  path: '/armada',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/area-layanan': typeof AreaLayananRoute
  '/armada': typeof ArmadaRoute
  '/faq': typeof FaqRoute
  '/tentang-kami': typeof TentangKamiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/area-layanan': typeof AreaLayananRoute
  '/armada': typeof ArmadaRoute
  '/faq': typeof FaqRoute
  '/tentang-kami': typeof TentangKamiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/area-layanan': typeof AreaLayananRoute
  '/armada': typeof ArmadaRoute
  '/faq': typeof FaqRoute
  '/tentang-kami': typeof TentangKamiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/area-layanan' | '/armada' | '/faq' | '/tentang-kami'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/area-layanan' | '/armada' | '/faq' | '/tentang-kami'
  id: '__root__' | '/' | '/area-layanan' | '/armada' | '/faq' | '/tentang-kami'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaLayananRoute: typeof AreaLayananRoute
  ArmadaRoute: typeof ArmadaRoute
  FaqRoute: typeof FaqRoute
  TentangKamiRoute: typeof TentangKamiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-layanan': {
      id: '/area-layanan'
      path: '/area-layanan'
      fullPath: '/area-layanan'
      preLoaderRoute: typeof AreaLayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/armada': {
      id: '/armada'
      path: '/armada'
      fullPath: '/armada'
      preLoaderRoute: typeof ArmadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaLayananRoute: AreaLayananRoute,
  ArmadaRoute: ArmadaRoute,
  FaqRoute: FaqRoute,
  TentangKamiRoute: TentangKamiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
